FROM python

RUN pip install flask psycopg-binary

WORKDIR /opt/flask

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

#COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]