services:
  organology-database:
    image: organology-database
    container_name: organology-database
    hostname: organology-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"

  organology-portal:
    image: organology-portal
    container_name: organology-portal
    hostname: organology-portal
    volumes:
      - ../www/flask:/opt/flask
    ports:
    - "5000:5000"

# TODO: podman cannot handle 127.0.0.1:5432:5432