-- auto generated by ../utils/generate_notes_ipn.sh
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('C','','Do','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('C#','','Do#','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('D','','Re','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('D#','','Re#','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('E','','Mi','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('F','','Fa','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('F#','','Fa#','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('G','','Sol','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('G#','','Sol#','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('A','','La','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('A#','','La#','');
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as) VALUES ('B','H','Si','Ti');
