-- auto generated by ./utils/./generate_notes_ipn.sh
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('C','','Do','',-9);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('C#','','Do#','',-8);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('D','','Re','',-7);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('D#','','Re#','',-6);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('E','','Mi','',-5);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('F','','Fa','',-4);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('F#','','Fa#','',-3);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('G','','Sol','',-2);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('G#','','Sol#','',-1);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('A','','La','',0);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('A#','','La#','',1);
INSERT INTO music.notes (note,note_also_known_as,solfege,solfege_also_known_as,semitones_from_A4) VALUES ('B','H','Si','Ti',2);
